
spring:
  thymeleaf:
#    开发时候建议关闭缓存
    cache: false
#  quartz:
#    dsname
#    job-store-type: jdbc
#  mail:
#    host: smtp.sina.com
#    port: 465
#    username: 7jczhou@sina.com
#    password: zhouchao123+.
#    protocol: smtps
#    properties:
#      mail:
server:
  servlet:
    context-path:
